
import * as dotenv from 'dotenv';
dotenv.config();

import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { products } from './schema/products';
import { carts } from './schema/carts';
import { orders, orderItems } from './schema/orders';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const dummyProducts = [
  // Electronics (Existing & Expanded) - 8 items
  {
    title: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones, Black',
    description: 'Industry-leading noise cancellation, 30-hour battery life, and crystal-clear hands-free calling.',
    price: '348.00',
    rating: '4.8',
    reviewCount: 12500,
    image: 'https://placehold.co/600x600?text=Sony+Headphones',
    images: ['https://placehold.co/600x600?text=Sony+Back', 'https://placehold.co/600x600?text=Sony+Side'],
    category: 'Electronics',
    stock: 50,
    isPrime: true,
  },
  {
    title: 'Apple iPad Air (5th Generation): with M1 chip, 10.9-inch Liquid Retina Display, 64GB, Space Gray',
    description: 'Immersive 10.9-inch Liquid Retina display. 12MP Wide back camera, 12MP Ultra Wide front camera.',
    price: '559.00',
    rating: '4.9',
    reviewCount: 9800,
    image: 'https://placehold.co/600x600?text=iPad+Air',
    images: ['https://placehold.co/600x600?text=iPad+Side'],
    category: 'Electronics',
    stock: 120,
    isPrime: true,
  },
  {
    title: 'Logitech MX Master 3S - Wireless Performance Mouse, Ultra-Fast Scrolling, Ergo, 8K DPI',
    description: 'Any-surface tracking - now 8K DPI: Use MX Master 3S cordless computer mouse to work on any surface - even glass.',
    price: '99.99',
    rating: '4.7',
    reviewCount: 8500,
    image: 'https://placehold.co/600x600?text=MX+Master+3S',
    images: ['https://placehold.co/600x600?text=Mouse+Side'],
    category: 'Electronics',
    stock: 200,
    isPrime: true,
  },
  {
    title: 'Samsung T7 Shield 2TB, Portable SSD, Photographer, 1050MB/s, Rugged, USBC',
    description: 'Rugged durability: Tough, fast, and compact, the all new PSSD T7 Shield gives you superior performance on the go.',
    price: '119.99',
    rating: '4.8',
    reviewCount: 4500,
    image: 'https://placehold.co/600x600?text=Samsung+SSD',
    images: ['https://placehold.co/600x600?text=SSD+Angle'],
    category: 'Electronics',
    stock: 80,
    isPrime: true,
  },
  {
    title: 'Anker USB C Charger, 735 Charger (Nano II 65W), 3-Port Fast Compact Wall Sockets',
    description: 'The Only Charger You Need: Say goodbye to your old power bricks. Anker 735 Charger (Nano II 65W) has the power you need.',
    price: '39.99',
    rating: '4.8',
    reviewCount: 15600,
    image: 'https://placehold.co/600x600?text=Anker+Charger',
    images: ['https://placehold.co/600x600?text=Charger+Ports'],
    category: 'Electronics',
    stock: 300,
    isPrime: true,
  },
  {
    title: 'Kindle Paperwhite (16 GB) – Now with a 6.8" display and adjustable warm light',
    description: 'All-new Kindle Paperwhite – Now with a 6.8” display and thinner borders, adjustable warm light, up to 10 weeks of battery life.',
    price: '149.99',
    rating: '4.7',
    reviewCount: 32000,
    image: 'https://placehold.co/600x600?text=Kindle+Paperwhite',
    images: ['https://placehold.co/600x600?text=Kindle+Reading'],
    category: 'Electronics',
    stock: 150,
    isPrime: true,
  },
  {
    title: 'Roku Streaming Stick 4K | Portable Roku Streaming Device 4K/HDR/Dolby Vision',
    description: 'Hides behind your TV: The all-new design plugs right into your TV with a simple setup.',
    price: '39.00',
    rating: '4.6',
    reviewCount: 54000,
    image: 'https://placehold.co/600x600?text=Roku+Stick',
    images: ['https://placehold.co/600x600?text=Roku+Remote'],
    category: 'Electronics',
    stock: 500,
    isPrime: false,
  },
  {
    title: 'GoPro HERO12 Black - Waterproof Action Camera with 5.3K60 Ultra HD Video',
    description: 'Incredible image quality, HyperSmooth 6.0 video stabilization and huge battery life boost.',
    price: '349.00',
    rating: '4.5',
    reviewCount: 2100,
    image: 'https://placehold.co/600x600?text=GoPro+Hero12',
    images: [],
    category: 'Electronics',
    stock: 60,
    isPrime: true,
  },

  // Computers (New) - 5 items
  {
    title: 'Apple MacBook Air 15-inch Laptop with M2 chip: 15.3-inch Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage',
    description: 'Impossibly thin and incredibly fast M2 chip. All-day battery life and a stunning Liquid Retina display.',
    price: '1099.00',
    rating: '4.8',
    reviewCount: 1500,
    image: 'https://placehold.co/600x600?text=MacBook+Air',
    images: ['https://placehold.co/600x600?text=MacBook+Side'],
    category: 'Computers',
    stock: 45,
    isPrime: true,
  },
  {
    title: 'Acer Aspire 5 Slim Laptop, 15.6 inches Full HD IPS Display, AMD Ryzen 3 3200U',
    description: 'Powerful and portable, the Aspire 5 delivers on every aspect of everyday computing.',
    price: '299.99',
    rating: '4.3',
    reviewCount: 35000,
    image: 'https://placehold.co/600x600?text=Acer+Laptop',
    images: [],
    category: 'Computers',
    stock: 200,
    isPrime: true,
  },
  {
    title: 'Dell Inspiron 15 3000 Series 3511 Laptop, 15.6" FHD Touchscreen, Intel Core i5-1135G7',
    description: 'Designed running more efficiently and more reliably at faster speeds.',
    price: '529.00',
    rating: '4.4',
    reviewCount: 890,
    image: 'https://placehold.co/600x600?text=Dell+Inspiron',
    images: [],
    category: 'Computers',
    stock: 75,
    isPrime: false,
  },
  {
    title: 'ASUS TUF Gaming F15 Gaming Laptop, 15.6” 144Hz FHD IPS-Type Display, Intel Core i5-10300H',
    description: 'Geared for serious gaming and real-world durability, the TUF Gaming F15 is a fully-loaded Windows 10 Pro gaming laptop.',
    price: '649.99',
    rating: '4.6',
    reviewCount: 5400,
    image: 'https://placehold.co/600x600?text=ASUS+Gaming',
    images: [],
    category: 'Computers',
    stock: 60,
    isPrime: true,
  },
  {
    title: 'HP Pavilion 15 Laptop, 11th Gen Intel Core i7-1165G7, 16 GB RAM, 512 GB SSD',
    description: 'Enjoy mind-blowing entertainment with a micro-edge screen and Audio by B&O.',
    price: '785.00',
    rating: '4.5',
    reviewCount: 1200,
    image: 'https://placehold.co/600x600?text=HP+Pavilion',
    images: [],
    category: 'Computers',
    stock: 90,
    isPrime: true,
  },

  // Smart Home (Expanded) - 5 items
  {
    title: 'Echo Dot (5th Gen, 2022 release) | With bigger vibrant sound, helpful routines and Alexa',
    description: 'Our best sounding Echo Dot yet – Enjoy an improved audio experience compared to any previous Echo Dot.',
    price: '49.99',
    rating: '4.7',
    reviewCount: 65000,
    image: 'https://placehold.co/600x600?text=Echo+Dot',
    images: [],
    category: 'Smart Home',
    stock: 1000,
    isPrime: true,
  },
  {
    title: 'Ring Video Doorbell – 1080p HD video, improved motion detection, easy installation',
    description: 'See, hear, and speak to anyone at your door from your phone, tablet, or PC.',
    price: '99.99',
    rating: '4.6',
    reviewCount: 145000,
    image: 'https://placehold.co/600x600?text=Ring+Doorbell',
    images: [],
    category: 'Smart Home',
    stock: 300,
    isPrime: true,
  },
  {
    title: 'Philips Hue White and Color Ambiance A19 E26 LED Smart Bulb, Bluetooth & Zigbee',
    description: 'Go bright, go bold with millions of colors and shades of white light, synced to your music and movies.',
    price: '44.99',
    rating: '4.7',
    reviewCount: 12000,
    image: 'https://placehold.co/600x600?text=Philips+Hue',
    images: [],
    category: 'Smart Home',
    stock: 500,
    isPrime: true,
  },
  {
    title: 'Kasa Smart Plug HS103P4, Smart Home Wi-Fi Outlet Works with Alexa, Echo, Google Home',
    description: 'Control your appliances from anywhere. Voice control with Alexa and Google Assistant.',
    price: '24.99',
    rating: '4.8',
    reviewCount: 34000,
    image: 'https://placehold.co/600x600?text=Kasa+Plug',
    images: [],
    category: 'Smart Home',
    stock: 600,
    isPrime: true,
  },
  {
    title: 'Google Nest Thermostat - Smart Thermostat for Home - Programmable Wifi Thermostat',
    description: 'Energy saving smart thermostat that turns itself down when you leave the house.',
    price: '115.00',
    rating: '4.5',
    reviewCount: 18000,
    image: 'https://placehold.co/600x600?text=Nest+Thermostat',
    images: [],
    category: 'Smart Home',
    stock: 150,
    isPrime: true,
  },

  // Arts & Crafts (New) - 5 items
  {
    title: 'Crayola Inspiration Art Case Coloring Set, Kids Art Supplies, 140 Count',
    description: 'Premier art storage case with 140 pieces, including crayons, pencils, and markers.',
    price: '29.99',
    rating: '4.8',
    reviewCount: 45000,
    image: 'https://placehold.co/600x600?text=Crayola+Set',
    images: [],
    category: 'Arts & Crafts',
    stock: 400,
    isPrime: true,
  },
  {
    title: 'Singer 4423 Heavy Duty Sewing Machine With Included Accessory Kit',
    description: '23 built-in stitches, automatic needle threader, and heavy duty metal frame.',
    price: '199.99',
    rating: '4.6',
    reviewCount: 22000,
    image: 'https://placehold.co/600x600?text=Singer+Sewing',
    images: [],
    category: 'Arts & Crafts',
    stock: 80,
    isPrime: true,
  },
  {
    title: 'Prismacolor Premier Colored Pencils, Soft Core, 72 Pack',
    description: 'Soft, thick cores are perfect for shading and shadows. Ultra-smooth color laydown.',
    price: '54.00',
    rating: '4.9',
    reviewCount: 38000,
    image: 'https://placehold.co/600x600?text=Prismacolor',
    images: [],
    category: 'Arts & Crafts',
    stock: 250,
    isPrime: true,
  },
  {
    title: 'Liquitex BASICS Acrylic Paint, 48-Piece Set, 22ml Tubes',
    description: 'Thick, creamy with satin finish; Good pigment load.',
    price: '45.00',
    rating: '4.8',
    reviewCount: 8900,
    image: 'https://placehold.co/600x600?text=Acrylic+Paint',
    images: [],
    category: 'Arts & Crafts',
    stock: 120,
    isPrime: true,
  },
  {
    title: 'Cricut Explore 3 Machine - Smart Cutting Machine, 2X Faster & 10X Force',
    description: 'Cut, draw, score, and more with the ultimate DIY machine.',
    price: '249.00',
    rating: '4.8',
    reviewCount: 12500,
    image: 'https://placehold.co/600x600?text=Cricut+Machine',
    images: [],
    category: 'Arts & Crafts',
    stock: 50,
    isPrime: true,
  },

  // Books (Existing & Expanded) - 8 items
  {
    title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving--every day.',
    price: '13.79',
    rating: '4.9',
    reviewCount: 110000,
    image: 'https://placehold.co/600x600?text=Atomic+Habits',
    images: [],
    category: 'Books',
    stock: 1000,
    isPrime: true,
  },
  {
    title: 'The Psychology of Money: Timeless lessons on wealth, greed, and happiness',
    description: 'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach.',
    price: '10.50',
    rating: '4.8',
    reviewCount: 65000,
    image: 'https://placehold.co/600x600?text=Psychology+of+Money',
    images: [],
    category: 'Books',
    stock: 750,
    isPrime: true,
  },
  {
    title: 'Project Hail Mary: A Novel by Andy Weir',
    description: 'A lone astronaut must save the earth from disaster in this incredible new science-fiction thriller from the #1 New York Times bestselling author of The Martian.',
    price: '14.50',
    rating: '4.9',
    reviewCount: 60000,
    image: 'https://placehold.co/600x600?text=Project+Hail+Mary',
    images: [],
    category: 'Books',
    stock: 400,
    isPrime: true,
  },
  {
    title: 'Deep Work: Rules for Focused Success in a Distracted World',
    description: 'Deep work is the ability to focus without distraction on a cognitively demanding task.',
    price: '12.00',
    rating: '4.6',
    reviewCount: 12000,
    image: 'https://placehold.co/600x600?text=Deep+Work',
    images: [],
    category: 'Books',
    stock: 300,
    isPrime: false,
  },
  {
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    description: 'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees.',
    price: '45.00',
    rating: '4.7',
    reviewCount: 7000,
    image: 'https://placehold.co/600x600?text=Clean+Code',
    images: [],
    category: 'Books',
    stock: 150,
    isPrime: true,
  },
  {
    title: 'The 48 Laws of Power by Robert Greene',
    description: 'Amoral, cunning, ruthless, and instructive, this multi-million-copy New York Times bestseller is the definitive manual for anyone interested in gaining, observing, or defending against ultimate control.',
    price: '16.99',
    rating: '4.7',
    reviewCount: 85000,
    image: 'https://placehold.co/600x600?text=48+Laws+of+Power',
    images: [],
    category: 'Books',
    stock: 600,
    isPrime: true,
  },
  {
    title: 'Thinking, Fast and Slow by Daniel Kahneman',
    description: 'The major New York Times bestseller that has captivated the world: explains the two systems that drive the way we think.',
    price: '14.99',
    rating: '4.6',
    reviewCount: 35000,
    image: 'https://placehold.co/600x600?text=Thinking+Fast+Slow',
    images: [],
    category: 'Books',
    stock: 400,
    isPrime: true,
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    description: 'In Sapiens, Dr Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical – and sometimes devastating – breakthroughs of the Cognitive, Agricultural and Scientific Revolutions.',
    price: '15.50',
    rating: '4.7',
    reviewCount: 68000,
    image: 'https://placehold.co/600x600?text=Sapiens',
    images: [],
    category: 'Books',
    stock: 500,
    isPrime: true,
  },

  // Home (Existing) - 7 items
  {
    title: 'Dyson V15 Detect Cordless Vacuum Cleaner',
    description: 'Dyson’s most powerful, intelligent cordless vacuum. Laser reveals microscopic dust.',
    price: '649.99',
    rating: '4.6',
    reviewCount: 3400,
    image: 'https://placehold.co/600x600?text=Dyson+V15',
    images: ['https://placehold.co/600x600?text=Dyson+Action'],
    category: 'Home',
    stock: 40,
    isPrime: true,
  },
  {
    title: 'Instant Pot Pro 10-in-1 Pressure Cooker, Slow Cooker, Rice/Grain Cooker',
    description: '10-in-1 pressure cooker, slow cooker, rice/grain cooker, streamer, sauté, sous vide, yogurt maker, sterilizer, and warmer.',
    price: '129.95',
    rating: '4.7',
    reviewCount: 22000,
    image: 'https://placehold.co/600x600?text=Instant+Pot',
    images: ['https://placehold.co/600x600?text=Instant+Pot+Food'],
    category: 'Home',
    stock: 250,
    isPrime: true,
  },
  {
    title: 'Keurig K-Elite Single Serve K-Cup Pod Coffee Maker, Brushed Slate',
    description: 'Premium finish and programmable features deliver a modern design and the ultimate beverage customization.',
    price: '145.00',
    rating: '4.8',
    reviewCount: 41000,
    image: 'https://placehold.co/600x600?text=Keurig+Coffee',
    images: [],
    category: 'Home',
    stock: 180,
    isPrime: true,
  },
  {
    title: 'Shark NV360 Navigator Lift-Away Deluxe Upright Vacuum with Large Dust Cup',
    description: 'Lift-Away Pod: Detachable pod for cleaning stairs, furniture, and more.',
    price: '159.99',
    rating: '4.5',
    reviewCount: 18000,
    image: 'https://placehold.co/600x600?text=Shark+Vacuum',
    images: [],
    category: 'Home',
    stock: 100,
    isPrime: true,
  },
  {
    title: 'DeWalt 20V MAX Cordless Drill / Driver Kit, Compact, 1/2-Inch',
    description: 'Compact, lightweight design fits into tight areas. High performance motor delivers 300 unit watts out (UWO) of power ability.',
    price: '99.00',
    rating: '4.9',
    reviewCount: 41000,
    image: 'https://placehold.co/600x600?text=DeWalt+Drill',
    images: ['https://placehold.co/600x600?text=Drill+Action'],
    category: 'Home',
    stock: 200,
    isPrime: true,
  },
  {
    title: 'Ninja AF101 Air Fryer that Crisps, Roasts, Reheats, & Dehydrates',
    description: 'Now you can enjoy guilt-free food. Air fry with up to 75% less fat than traditional frying methods.',
    price: '99.99',
    rating: '4.8',
    reviewCount: 56000,
    image: 'https://placehold.co/600x600?text=Ninja+Air+Fryer',
    images: [],
    category: 'Home',
    stock: 300,
    isPrime: true,
  },
  {
    title: 'YETI Rambler 20 oz Travel Mug, Stainless Steel, Vacuum Insulated',
    description: 'The Rambler 20 oz. Travel Mug is made from durable stainless steel with double-wall vacuum insulation to protect your hot or cold beverage at all costs.',
    price: '35.00',
    rating: '4.9',
    reviewCount: 9500,
    image: 'https://placehold.co/600x600?text=YETI+Mug',
    images: [],
    category: 'Home',
    stock: 450,
    isPrime: true,
  },

  // Fashion (New) - 5 items
  {
    title: 'Carhartt Men\'s Loose Fit Heavyweight Short-Sleeve Pocket T-Shirt',
    description: 'Rib-knit crewneck that holds its shape throughout the workday.',
    price: '19.99',
    rating: '4.6',
    reviewCount: 88000,
    image: 'https://placehold.co/600x600?text=Carhartt+Shirt',
    images: [],
    category: 'Fashion',
    stock: 800,
    isPrime: true,
  },
  {
    title: 'Adidas Men\'s Daily 3.0 Skate Shoe',
    description: 'Men\'s skate-inspired shoes for every day.',
    price: '65.00',
    rating: '4.7',
    reviewCount: 15000,
    image: 'https://placehold.co/600x600?text=Adidas+Shoe',
    images: [],
    category: 'Fashion',
    stock: 120,
    isPrime: true,
  },
  {
    title: 'Hanes Women\'s EcoSmart Crewneck Sweatshirt',
    description: 'Soft, plush, 50% cotton/50% polyester fleece.',
    price: '15.00',
    rating: '4.5',
    reviewCount: 42000,
    image: 'https://placehold.co/600x600?text=Hanes+Sweatshirt',
    images: [],
    category: 'Fashion',
    stock: 300,
    isPrime: false,
  },
  {
    title: 'Ray-Ban RB2140 Original Wayfarer Sunglasses',
    description: 'Classic Wayfarer sunglasses featuring crystal glass lenses and a durable acetate frame.',
    price: '163.00',
    rating: '4.6',
    reviewCount: 14000,
    image: 'https://placehold.co/600x600?text=RayBan+Wayfarer',
    images: [],
    category: 'Fashion',
    stock: 60,
    isPrime: true,
  },
  {
    title: 'Levi\'s Men\'s 501 Original Fit Jeans',
    description: 'The original blue jean since 1873. Original straight fit.',
    price: '79.50',
    rating: '4.4',
    reviewCount: 56000,
    image: 'https://placehold.co/600x600?text=Levis+501',
    images: [],
    category: 'Fashion',
    stock: 150,
    isPrime: true,
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  try {
    // Clean up existing data
    console.log('Cleaning up existing data...');
    // Order matters for foreign key constraints
    await db.delete(orderItems);
    await db.delete(orders);
    await db.delete(carts);
    await db.delete(products);
    console.log('Deleted existing data.');

    // Insert products
    console.log('Inserting products...');
    await db.insert(products).values(dummyProducts);
    
    console.log(`✅ Database seeded successfully with ${dummyProducts.length} products`);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  } finally {
    process.exit(0);
  }
}

main();
